language: generic 
os: linux
services:
    - docker 

before_install:
    - docker build -t cshorne/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true cshorne/docker-react npm run test

# Tell Travis CI to deploy to production using elasticbeanstalk service on AWS
deploy:
    provider: elasticbeanstalk
    edge: true
    skip_cleanup: true # Prevents Travis deleting build output before it uploads to S3
#   access_key_id: "AKIAZROBUX727LHJICNW"
    access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
    secret_access_key: "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"
    region: 'us-east-2'
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "arn:aws:s3:::elasticbeanstalk-us-east-2-655925493749"
    bucket_path: "docker-react"
    on:
        branch: master # This tells Travis to only deploy when we update the master branch

#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key: $AWS_SECRET_KEY

#        access_key_id: 
#            secure: $AWS_ACCESS_KEY
#        secret_access_key:
#            secure: $AWS_SECRET_KEY
    
