language: generic 
os: linux
services:
    - docker 

before_install:
    - docker build -t cshorne/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true cshorne/docker-react npm run test

# Tell Travis CI to deploy to production using elasticbeanstalk service on AWS
deploy:
    provider: elasticbeanstalk
    edge: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket: "elasticbeanstalk-us-east-2-655925493749"
    bucket_path: "docker-react"
    on:
        branch: master # This tells Travis to only deploy when we update the master branch